name: bookapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  firebase_database: ^9.0.9
  firebase_messaging: ^11.2.12
  firebase_storage: ^10.2.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.0
  get: ^4.6.1
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  media_picker_widget: ^0.0.7
  mpesa: ^2.0.2
  open_file: ^3.2.1
  pdf: ^3.7.4
  provider: ^6.0.2
  readmore: ^2.1.0
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Gideon_Roman
      fonts:
        - asset: assets/fonts/GideonRoman-Regular.ttf

    - family: Noto_Serif
      fonts:
        - asset: assets/fonts/NotoSerifDisplay-Regular.ttf

    - family: Redressed
      fonts:
        - asset: assets/fonts/Redressed-Regular.ttf
