// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFdTxT3Nz8AI_AXF1dAcWG-qzOMY7yI8k',
    appId: '1:284391872417:web:5e6961c2b8c2c1467a5de0',
    messagingSenderId: '284391872417',
    projectId: 'bookapp-2728a',
    authDomain: 'bookapp-2728a.firebaseapp.com',
    storageBucket: 'bookapp-2728a.appspot.com',
    measurementId: 'G-CZFR3Z0CLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRUhiUGyoudeRXMC5rzt1fEzsVNMTeAI',
    appId: '1:284391872417:android:ea7ddc2d1d63716f7a5de0',
    messagingSenderId: '284391872417',
    projectId: 'bookapp-2728a',
    storageBucket: 'bookapp-2728a.appspot.com',
  );
}
